### ISSUE TITLE
Animation is broken in Blender and Unity after "Create VAT"

### ISSUE THREAD

**Issue by KD-VFX** [sharpen3d/openvat#1]
I'm sorry, I wrote "It worked!" in Blender extension website, that was mistake. It doesn't work.
I could export data, import to Unity, generate prefabs and play. 
But result is failed.
Do you know why?

https://github.com/user-attachments/assets/155cc5ee-6e36-4cdd-910e-81790e927b30

https://github.com/user-attachments/assets/23bb278c-b4cc-4b7b-b2dd-6b9f11bddb7b

https://github.com/user-attachments/assets/e43a63b0-8870-4e9c-9f41-4f6dd6445ea1

**Comment by sharpen3d** [comment]
I see the issue in your before openVAT video. I do not currently support animation with vertex order change or face recalculation with openVAT. So as you simulate fluid and the amount of verts changes as well as the connections between the verts, this is not currently possible to encode and decode properly. 

If you turn this simulation into a point cloud and ensure it maintains the same amount of points in the same order, it's possible you could encode the result, but I know that's not what you are after.

**Comment by sharpen3d** [comment]
If you'd like to upload the .blend- or send to stilson.luke@gmail.com - I can try to see any workarounds I might suggest

**Comment by KD-VFX** [comment]
[Liquid_Domain.zip](https://github.com/user-attachments/files/17618727/Liquid_Domain.zip)
Thank you very much!
I uploaded blend file. It is made with Blender 4.2.

**Comment by KD-VFX** [comment]
And thank you for your answer. I understand.
OpenVAT does not currently support fluid simulation, and should be used for things like cloth simulation.
It would be great if OpenVAT supported fluid simulation.

**Comment by sharpen3d** [comment]
Would you mind including the bake cache `//simm_beforeApply_20241101_2.abc`
It's good and thought-provoking for me to try and provide some kind of solution (or at least warning) in the plugin for these kind of cases

**Comment by KD-VFX** [comment]
[simm_beforeApply_20241101_2.zip](https://github.com/user-attachments/files/17620340/simm_beforeApply_20241101_2.zip)
