### ISSUE TITLE
need help writing a VAT shader for Godot engine.

### ISSUE THREAD

**Issue by Mohammad9760** [sharpen3d/openvat#2]
I need help understanding how the VAT is packed.
if I have say 50 frames and 200 vertecies, the usual VAT should end up 200x50 pixels, however this extension does pack it into a square image.
I have used a VAT shader from this [demo](https://github.com/yanorax/Godot-VertexAnimation-Demo).
however VATs baked using this extension doesn't work, I figured the shader here expects the VAT to have frame as height and vertID as width.

a suggestion is to have an option for not baking a square image and instead just do time=row, vertex=column.
thanks.

**Comment by Mohammad9760** [comment]
ooops, I didn't see the Engine Tools folder LOL

**Comment by Mohammad9760** [comment]
ooops, I didn't see the Engine Tools folder LOL

**Comment by sharpen3d** [comment]
ha, I actually just recently added this, let me know if you have any issues with this as I am not as well versed in GoDot as Unity and Unreal. 

On another note, I'm not sure if you have tried this, but when creating the vat there's a few ways you can get explicit additional details about what is happening. If you uncheck 'perform cleanup' you can investigate the geometry nodes that are used to create the vat within an additional scene which is made. 

Additionally, the blender shader that is created when the vat is created is well-commented and should give some additional insight into shaders in different software
